name: Terraform apply

on:
  workflow_call:
    inputs:
      target_env:
        required: true
        type: string
      working_directory:
        required: true
        type: string
      plan_commit_sha:
        required: true
        type: string
      plan_artifact_name:
        required: true
        type: string
      change_ref:
        required: true
        type: string

permissions:
  contents: read
  id-token: write

jobs:
  apply:
    runs-on: [self-hosted, Windows]
    environment: ${{ inputs.target_env }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.plan_commit_sha }}
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
         terraform_version: 1.6.6
         terraform_wrapper: false

      - uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.plan_artifact_name }}
          path: ${{ inputs.working_directory }}

      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - shell: powershell
        working-directory: ${{ inputs.working_directory }}
        run: |
          terraform init
          terraform apply -auto-approve tfplan.binary
``
