
name: Terraform plan

on:
  workflow_call:
    inputs:
      target_env:
        required: true
        type: string
      selected_branch:
        required: true
        type: string
      working_directory:
        required: true
        type: string
      change_ref:
        required: true
        type: string
      change_reason:
        required: true
        type: string
      rollback_plan:
        required: true
        type: string
    outputs:
      plan_commit_sha:
        value: ${{ jobs.plan.outputs.plan_commit_sha }}
      plan_artifact_name:
        value: ${{ jobs.plan.outputs.plan_artifact_name }}

permissions:
  contents: read
  id-token: write

jobs:
  plan:
    runs-on: windows-latest
    environment: ${{ inputs.target_env }}

    outputs:
      plan_commit_sha: ${{ steps.sha.outputs.sha }}
      plan_artifact_name: ${{ steps.art.outputs.name }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.selected_branch }}

      
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6
          terraform_wrapper: false


      - id: sha
        shell: powershell
        run: |
          "sha=$(git rev-parse HEAD)" >> $env:GITHUB_OUTPUT

      - id: art
        shell: powershell
        run: |
          "name=tfplan-${{ github.run_id }}" >> $env:GITHUB_OUTPUT

      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - shell: powershell
        working-directory: ${{ inputs.working_directory }}
        run: |
          terraform init
          terraform fmt -check
          terraform validate
          terraform plan -out=tfplan.binary

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.art.outputs.name }}
          path: ${{ inputs.working_directory }}/tfplan.binary
